Besu container check

diff --git a/.github/workflows/matrix-docker-test.yaml b/.github/workflows/matrix-docker-test.yaml
--- a/.github/workflows/matrix-docker-test.yaml
+++ b/.github/workflows/matrix-docker-test.yaml
@@ -20,10 +20,29 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
       
-      - run: |
+      - name: Start container
+        run: |
           docker run -d --rm --name besu hyperledger/besu:${{ inputs.tag }}
-          sleep 20
-          docker logs besu
-          docker stop besu
+ 
+      - name: Verify besu container
+        run: |
+          success=false
+          while [[ $success != "true" && $RETRY -gt 0 ]]
+          do
+            docker logs besu-check | grep -q "Ethereum main loop is up" && success=true
+            RETRY=$(expr $RETRY - 1)
+            echo "Waiting for the container to start. Remaining retries $RETRY ..."
+            sleep $SLEEP
+          done
 
+          docker rm -f besu-check > /dev/null
+          if [[ $success != "true" ]]
+          then
+            echo "Could not find the log message 'Ethereum main loop is up'"
+            exit 1
+          fi
+          exit 0
+        env:
+          SLEEP: 5
+          RETRY: 10
 
